// Generated by Wrangler by running `wrangler types` (hash: 869ac3b4ce0f52ba3b2e0bc70c49089e)
// Runtime types generated with workerd@1.20250823.0 2024-11-11
declare namespace Cloudflare {
  interface Env extends Record<string, undefined> {
    StateNonceKV: KVNamespace;
    CodeNonceKV: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {
  ISSUER_BASE_URL: string;
  JWT_PRIVATE_KEY_X509: string;
  JWT_PUBLIC_KEY_JWK: string;
  JWT_KEY_ID: string;
}
